name: pipeline
on: 
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "My first Job"
    runs-on: ubuntu-latest
    steps:
      - name: "My first action"
        run: echo "Hello World !!!"
      - name: "Second action"  
        run: |
          echo "You created the first workflow"
          echo "congrats !!!"
