name: pipeline
on: 
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  first-job:
    name: "First Job"
    runs-on: ubuntu-latest
    steps:
      - name: "First action"
        run: echo "Hello World !!!"
      - name: "Second action"  
        run: |
          echo "You created the first workflow"
          echo "congrats !!!"
  second-job:
    name: "Installation of the NodeJS environment"
    runs-on: ubuntu-latest
    steps:
      - name: "Verification of the current NodeJS version"
        run: node --version
      - name: "Definition of the version v25.2.1 of the NodeJS"  
      - uses: actions/setup-node@v6.0.0
        with:
          node-version: "25.2.1"
      - name: "Verification of the current version of NodeJS"  
        run: node --version
