name: pipeline
on: 
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  first-job:
    name: "First Job"
    runs-on: ubuntu-latest
    steps:
      - name: "First action"
        run: echo "Hello World !!!"
      - name: "Second action"  
        run: |
          echo "You created the first workflow"
          echo "congrats !!!"
  second-job:
    name: "Installation of the NodeJS environment"
    runs-on: ubuntu-latest
    steps:
      - name: "Verification of the current NodeJS version"
        run: node --version
